# Generated by Django 5.2 on 2025-05-07 04:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a product', max_length=200, unique=True)),
                ('price', models.FloatField(default=0.0, help_text='Price of the product', validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
    ]
