# Generated by Django 5.2 on 2025-05-08 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_options_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Approved'), ('d', 'Denied'), ('w', 'Waiting for approval')], default='w', help_text='Basket status', max_length=1),
        ),
    ]
